services:
  nginx:
    image: nginx:stable-alpine
    # ports:
    #   - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    # ports: 
    #   - "3000:3000"
    environment:
      - PORT=3000
      # - MONGO_USER=admin
      # - MONGO_PASSWORD=password
      # - MONGO_IP=mongo
      # - MONGO_PORT=27017
    depends_on:
      - mongo
    # networks:
    #   - app-network

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-data:/data/db
    # networks:
    #   - app-network

  redis:
    image: redis

    # networks:
    #   - app-network
volumes:
  mongo-data:

# networks:
#   app-network:
#     driver: bridge
