services:
  nginx:
    ports:
      - "80:80" 
    restart: always

  node-app:
    build:
      context: .
      args:
        - NODE_ENV=production 
    environment:
      - NODE_ENV=production
    command: ["npm", "run", "start"] 
    restart: always

  mongo:
    restart: always

  redis:
    restart: always
